### ISSUE TITLE
Incompatible with log4j-2.7

### ISSUE THREAD

**Issue by homeation** [rapid7/le_java#54]
The library throws an error when paired with log4j-2.7
2.6.2 is the last version that it works with.

**Comment by artgo** [comment]
This is an urgent issue for us because 2.7 introduced functionality we desperately need.

**Comment by artgo** [comment]
Please review the fix: https://github.com/rapid7/le_java/pull/56

**Comment by artgo** [comment]
We need to release new version to issue the fix

**Comment by stopal-r7** [comment]
@artgo this is released on maven, can you check and reopen if not resolved? Thanks.

**Comment by artgo** [comment]
Just tested - all good, thank you! :)
